eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: localhost
spring:
  application:
    name: post-service
  cloud:
    discovery:
      enabled: true
  data:
    mongodb:
      database: post_db
      port: 27017
server:
  port: 3010
